spring:
  cloud:
    default:
      producer:
        useNativeEncoding: true
      consumer:
        useNativeEncoding: true
    azure:
      namespace: james-event-hub-poc.servicebus.windows.net
      schema-group: kafka-sr-poc
    stream:
      kafka:
        binder:
          producer-properties:
            key.serializer: sample.consumer.AzureKafkaAvroSerializer
            value.serializer: sample.consumer.AzureKafkaAvroSerializer
          consumer-properties:
            key.deserializer: sample.consumer.AzureKafkaAvroDeserializer
            value.deserializer: sample.consumer.AzureKafkaAvroDeserializer
            specific.avro.reader: true
          min-partition-count: 2
          replicationFactor: 2
          brokers: james-event-hub-poc.servicebus.windows.net:9093
          configuration:
            sasl:
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://james-event-hub-poc.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=WNosDGCjXOLmB0kRExgj49c3OrC5YnqvBwzIf3TnQ5I=";
              mechanism: PLAIN
            security:
              protocol: SASL_SSL
      bindings:
        process-in-0:
          destination: my-random-topic2
      schema-registry-client:
        endpoint: http://localhost:8990
      schema:
        avro:
          schema-locations: classpath:avro/sensor.avsc
server.port: 9999
spring.cloud.stream.function.definition: process